server:
  port: 8082
spring:
  application:
    name: login
  mongodb:
    uri: mongodb+srv://teste:teste123@newcluster.xisxqqc.mongodb.net/Fatec
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.security: DEBUG